# Generated by Django 5.0.6 on 2024-06-07 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_department_student_course_interactiondata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PessimismPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(max_length=50)),
                ('attempts', models.IntegerField()),
                ('errors', models.IntegerField()),
                ('correct', models.IntegerField()),
                ('emotion', models.CharField(max_length=50)),
                ('head_pose', models.CharField(max_length=50)),
                ('pessimism_level', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
